services:
    marttiphpbb.calendarmulti.repo:
        class: marttiphpbb\calendarmulti\service\repo
        arguments:
            - '@dbal.conn'
            - '@content.visibility'
            - '@auth'
            - '@user'
            - '%core.table_prefix%'
            - '%tables.topics%'

    marttiphpbb.calendarmulti.tag_listener:
        class: marttiphpbb\calendarmulti\event\tag_listener
        arguments:
            - '@marttiphpbb.calendarmulti.repo'
        tags:
            - { name: event.listener }

    marttiphpbb.calendarmulti.input_listener:
        class: marttiphpbb\calendarmulti\event\input_listener
        arguments:
            - '@marttiphpbb.calendarmulti.repo'
        tags:
            - { name: event.listener }