services:
    marttiphpbb.calendarmulti:
        class: marttiphpbb\calendarmulti\repository\events
        arguments:
            - '@dbal.conn'
            - '@content.visibility'
            - '@auth'
            - '@user'
            - '@language'
            - '%tables.topics'
