services:
    marttiphpbb.calendarpoly.repo:
        class: marttiphpbb\calendarpoly\service\repo
        arguments:
            - '@dbal.conn'
            - '@content.visibility'
            - '@auth'
            - '@user'
            - '%core.table_prefix%'
            - '%tables.topics%'

    marttiphpbb.calendarpoly.tag_listener:
        class: marttiphpbb\calendarpoly\event\tag_listener
        arguments:
            - '@marttiphpbb.calendarpoly.repo'
        tags:
            - { name: event.listener }

    marttiphpbb.calendarpoly.input_listener:
        class: marttiphpbb\calendarpoly\event\input_listener
        arguments:
            - '@marttiphpbb.calendarpoly.repo'
        tags:
            - { name: event.listener }